Add "tablesOfContents" with unique id (#1237)
hbz/lobid-resources pull request #1249
Opened 2021-05-03 11:12 UTC by TobiasNx

See #1237

2021-05-03 13:08 UTC, dr0i requested changes
otherwise +1

2021-05-03 13:08 UTC, dr0i commented on src/main/resources/alma/common/fields.xml
> +          </data>
formatting seems broken

2021-05-03 13:08 UTC, dr0i commented
Also, if you like, try to solve conflicts.

2021-05-03 13:19 UTC, TobiasNx commented on src/main/resources/alma/common/fields.xml
> +          </data>
done

2021-05-03 15:04 UTC, dr0i commented
Ignore the fails checks - a play resource cannot be accessed atm.

2021-05-04 07:45 UTC, merged

2021-05-04 07:46 UTC, dr0i commented
See https://alma.lobid.org/resources/search?q=HT000161712&format=json. Closed.