Update the schema to https instead of http URLs
hbz/lobid-resources pull request #1346
Opened 2022-06-07 15:53 UTC by TobiasNx

Not only the transformation but also the schema needs to be updated.

https://github.com/hbz/lobid-resources/issues/1343

2022-06-08 11:33 UTC, TobiasNx commented
needed to add more changes to the transformation and the schema to get all `http` @dr0i could you have a look at the transformation why it fails? also @acka47 could you have a look at the schema changes?

2022-06-10 11:08 UTC, dr0i requested changes
See inline comments re verbosity. Haven't marked them all.

2022-06-10 11:08 UTC, dr0i commented on src/test/resources/alma/(CKB)5280000000199164.json
> +      "label" : "isb"
Why not keep the more verbose label?

2022-06-10 11:08 UTC, dr0i commented on src/test/resources/alma/(DE-605)HT000161712.json
>      }
dito verbose

2022-06-10 11:08 UTC, dr0i commented on src/test/resources/alma/(DE-605)HT004285445.json
>      }
better verbose

2022-06-10 11:08 UTC, dr0i commented on src/test/resources/alma/(DE-605)HT005207972.json
>      }
dito

2022-06-10 11:10 UTC, TobiasNx commented
> See inline comments re verbosity. Haven't marked them all.

This seems to be due to the labelmaker not knowing about the changes from http -> https.

2022-06-10 13:26 UTC, dr0i commented
@UBmakla or @hagbeck : is the change of `http` to `https` in some way affecting you, or doesn't it matter?

2022-06-10 13:34 UTC, acka47 commented
We should be careful about this. For DNB URIs and probably also for ZDB URIs this is fine as they switched to HTTPS URIs but MARC relators still use HTTP-only URIs (and do not provide a `sameAs` link or similar to the https URI), see e.g. https://id.loc.gov/vocabulary/relators/ill.html. So we should stick with that as this is important for the RDF representation.

2022-06-10 13:35 UTC, acka47 requested changes
As noted in the other comment, we should continue using http-only URIs for MARC relator codes.

2022-06-10 13:41 UTC, hagbeck commented
The change to `https` is ok as long as the resulting URLs are not broken then ;-) 
We are using parts of some URL fields for selections and need to update these rules in some cases. But this is ok.

2022-06-10 13:42 UTC, hagbeck commented
Btw.: URLs to table of contents provided by hbz are currently `http`-only, too.

2022-06-10 14:14 UTC, dr0i commented
Conclusion so far:
Be aware of the generic URIs - even if e.g. `curl -L  --header "accept: text/plain" 'https://id.loc.gov/vocabulary/relators/aut'` brings up the proper `ntriples`, it's not reflected in the underlying data as [@acka47 noted ](https://github.com/hbz/lobid-resources/pull/1346#issuecomment-1152368724) as you can see in the data and in the missing `sameAs`. That's also true for our own [RPB-Skos](http://purl.org/lobid/rpb).
After you have checked `https` is ok, I would recommend to add this `https` variants to the shared label files (rather than have a copy of it ) - because it makes things easier to handle and consume and easier to exchange the label files).

2022-06-22 08:09 UTC, closed without merging