1708-noteForRelations
hbz/lobid-resources pull request #1730
Opened 2023-05-04 12:01 UTC by TobiasNx

I added a note field to all realtions based on the elements 760-787$$i

The Info is often mostly redundant to the relation itself.

@blackwinter can you have a look.

2023-05-04 12:10 UTC, blackwinter requested changes

2023-05-04 12:10 UTC, blackwinter commented on src/main/resources/alma/fix/relatedRessourcesAndLinks.fix
> +    copy_field("$i.t","supplement[].$last.label")
This line is duplicated.

2023-05-04 14:21 UTC, blackwinter approved these changes
Thanks!

2023-05-04 14:27 UTC, TobiasNx commented
We should discuss if we want the redundant info. Beil. = supplement.

2023-05-04 14:28 UTC, blackwinter commented
> We should discuss if we want the redundant info. Beil. = supplement.

_We_ do, yes.

2023-05-08 08:09 UTC, dr0i commented
Is this ready to be merged @TobiasNx ? (Discussions can later be done in a (new) issue.)

2023-05-11 15:34 UTC, TobiasNx commented
This can be merged

2023-05-11 16:05 UTC, merged

2023-05-11 16:05 UTC, dr0i commented
Will be deployed next Monday.

2023-05-15 08:47 UTC, blackwinter commented
:+1: Thanks!