Add stockNumber #1670
hbz/lobid-resources pull request #1801
Opened 2023-06-20 07:44 UTC by TobiasNx

Please have a look.
I introduced stockNumber.

I was not sure if I should model this as an array of Objects to state the sources of the stockNumber too. Or just like this.

2023-06-20 09:02 UTC, dr0i commented
Issue is missing, I don't know the context. You modelled this field at root level. Is this OK? What is the difference to `callnumber` (which is modelled under the `item` subtree)?

2023-06-20 09:08 UTC, TobiasNx commented
> Issue is missing, I don't know the context. You modelled this field at root level. Is this OK? What is the difference to `callnumber` (which is modelled under the `item` subtree)?

This #1670

2023-06-20 09:34 UTC, dr0i commented
Thx for the reference.  Have you considered to put this field under `publication`?

2023-06-27 13:46 UTC, dr0i requested changes

2023-07-07 13:01 UTC, TobiasNx commented on src/main/resources/labels/context-labels.json
> +    "uri": "http://purl.org/lobid/lv#stockNumber"
Opend a PR now: https://github.com/hbz/lobid-vocabs/pull/178

2023-07-25 06:34 UTC, TobiasNx commented on src/main/resources/labels/context-labels.json
> +    "uri": "http://purl.org/lobid/lv#stockNumber"
Since it is part of lobid vocabs now. Done.

2023-07-25 06:35 UTC, merged