Support auto-complete suggestions created from multiple fields
hbz/lobid-resources pull request #2080
Opened 2024-10-07 15:58 UTC by fsteeg

Like in lobid-gnd: configure fields to use in the `format` param (e.g. `json:title,contribution`), or use `format=json:suggest` for default fields.

See https://jira.hbz-nrw.de/browse/RPB-141

Deployed to test: https://test.lobid.org/resources/api#auto-complete

2024-10-08 08:45 UTC, acka47 commented
This looks already very good. There is one place where we should probably improve it: When resources have multiple contributing agents, the list of names should be cut after the first person and an "et al." added (like in the lobid HTML result lists).

Example: https://test.lobid.org/resources/search?q=%22Enhancing%20space%20resilience%20through%20non-materiel%20means%20%22&format=json%3Asuggest

2024-10-08 08:45 UTC, acka47 requested changes
See my comment

2024-10-08 10:11 UTC, fsteeg commented
Hm, but isn't that example a case where we actually need all authors to select the correct entry?

2024-10-08 10:16 UTC, acka47 commented
Maybe we should just wait what RPB editors say.

2024-10-10 08:10 UTC, fsteeg commented
RPB editors are done with review, re-requesting review from @acka47 (request for @dr0i is still open).

https://jira.hbz-nrw.de/browse/RPB-141

2024-10-10 09:33 UTC, acka47 approved these changes
+1

2024-10-10 10:55 UTC, merged

2024-10-10 11:07 UTC, dr0i commented
Deployed to production, closed.